image: camerondevine/corerobotics:latest

stages:
   - build
   - test
   - wrap
   - deploy

build-lib:
  stage: build
  script: 
   - mkdir build && cd build
   - cmake ..
   - make
  dependencies: []
  artifacts:
    paths:
     - $CI_PROJECT_DIR/lib/*
    expire_in: 1 week

test-lib:
  stage: test
  script:
   - mkdir build && cd build
   - cmake -Dtests=true ..
   - make
   - $CI_PROJECT_DIR/bin/cr-tests
  dependencies:
   - build-lib

wrap-python:
  stage: wrap
  script:
    - mkdir build && cd build
    - cmake -Dpython=true ..
    - make
    - for file in $CI_PROJECT_DIR/bin/*.py; do
    - file
    - done
  dependencies:
    - build-lib

test-install:
  stage: deploy
  script:
    - mkdir build && cd build
    - cmake -Dtests=true ..
    - make && make install
    - ldconfig /usr/local/lib
    - cr-tests
  dependencies:
    - build-lib
    - test-lib

test-coverage:
  stage: deploy
  script:
    - apt-get update && apt-get -y install lcov curl
    - mkdir build && cd build
    - cmake -Dreport=true ..
    - cmake --build . --config Debug
    - ctest --output-on-failure
  after_script:
    # Create lcov report
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
    - lcov --list coverage.info
    # Uploading to CodeCov
    - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  dependencies:
    - build-lib
