#!/bin/bash

# defaults
py_version=python3

# check input args
while [ "$1" != "" ]; do
  case $1 in
    -3 | --python3 )
      shift
      py_version='python3'
      ;;
    -2 | --python2 )
      shift
      py_version='python'
      ;;
    esac
    shift
done

for f in *.py; do $py_version "$f"; done