#!/bin/bash

dir="$( cd "$(dirname "$0")" ; pwd -P )"

echo [CoreRobotics] This script pushes the corerobotics docker image to docker hub

docker build -t cr_image $dir/..

docker tag cr_image owan/corerobotics:cr-docker
docker push owan/corerobotics:cr-docker
