#!/bin/bash

echo [CoreRobotics] This script runs the corerobotics docker image

# pull cameron's image with swig
docker pull camerondevine/corerobotics

# start the sessions
docker run -it camerondevine/corerobotics

# clone corerobotics into the container
# git clone https://gitlab.com/powan/CoreRobotics.git


